=== Jhonfeter/jasa_transportasi/jasa_transportasi/src/jasa_transportasi/jasa_transportasi.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="Data_sopir">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="biodata"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="biodata">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nama"/>
                <xs:element ref="jenis_kelamin"/>
                <xs:element ref="asal"/>
                <xs:element ref="no_hp"/>
                <xs:element ref="kendaraan"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="nama">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:NCName">
                    <xs:attribute name="no_identitas" use="required" type="xs:integer"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="jenis_kelamin" type="xs:NCName"/>
    <xs:element name="asal" type="xs:NCName"/>
    <xs:element name="no_hp">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:integer">
                    <xs:attribute name="code" use="required" type="xs:integer"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="kendaraan">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="jurusan"/>
                <xs:element ref="identitas_mobil"/>
                <xs:element ref="maks_penumpang" maxOccurs="30"/>
                <xs:element ref="maks_barang" maxOccurs="60"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="jurusan">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:NCName">
                    <xs:attribute name="no.sim" use="required" type="xs:integer"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="identitas_mobil">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:NCName">
                    <xs:attribute name="plat" use="required" type="xs:NCName"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="maks_penumpang">
    	<xs:simpleType>
    		<xs:restriction base="xs:integer">


    			<xs:maxInclusive value="30"></xs:maxInclusive>
    			<xs:minInclusive value="1"></xs:minInclusive>
    		</xs:restriction>
    	</xs:simpleType>
    </xs:element>
    <xs:element name="maks_barang">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:integer">
                    <xs:attribute name="satuan" use="required" type="xs:NCName"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Jhonfeter/jasa_transportasi/jasa_transportasi/bin/jasa_transportasi/jasa_transportasi.xml
<?xml version="1.0" encoding="UTF-8"?>
<Data_sopir xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="jasa_transportasi.xsd">
	<biodata>
		<nama no_identitas="112001">Jhon</nama>
		<jenis_kelamin>laki-laki</jenis_kelamin>
		<asal>Medan</asal>
		<no_hp code="+62">081210689244</no_hp>
		<kendaraan>
		<jurusan no.sim="11200001">Medan-Jakarta</jurusan>
		<identitas_mobil plat="BK">Counter</identitas_mobil>
		<maks_penumpang>30</maks_penumpang>
		<maks_barang satuan="kg">70</maks_barang>
		</kendaraan>
	</biodata>
	<biodata>
		<nama no_identitas="112002">Herman</nama>
		<jenis_kelamin>laki-laki</jenis_kelamin>
		<asal>surabaya</asal>
		<no_hp code="+62">081210689245</no_hp>
		<kendaraan>
		<jurusan no.sim="11200001">surabaya-medan</jurusan>
		<identitas_mobil plat="DX">Counter</identitas_mobil>
		<maks_penumpang>30</maks_penumpang>
		<maks_barang satuan="kg">60</maks_barang>
		</kendaraan>
	</biodata>
	<biodata>
		<nama no_identitas="112005">Tomy</nama>
		<jenis_kelamin>laki-laki</jenis_kelamin>
		<asal>jakarta</asal>
		<no_hp code="+62">08121068923</no_hp>
		<kendaraan>
		<jurusan no.sim="11200001">Medan-Jakarta</jurusan>
		<identitas_mobil plat="D">Counter</identitas_mobil>
		<maks_penumpang>30</maks_penumpang>
		<maks_barang satuan="kg">60</maks_barang>
		</kendaraan>
	</biodata>
	<biodata>
		<nama no_identitas="112001">Rifa</nama>
		<jenis_kelamin>laki-laki</jenis_kelamin>
		<asal>tasikmalaya</asal>
		<no_hp code="+62">08121068444</no_hp>
		<kendaraan>
		<jurusan no.sim="11200001">Tasikmalaya-jakarta</jurusan>
		<identitas_mobil plat="D">Counter</identitas_mobil>
		<maks_penumpang>30</maks_penumpang>
		<maks_barang satuan="kg">60</maks_barang>
		</kendaraan>
	</biodata>
	<biodata>
		<nama no_identitas="1120033">Wady</nama>
		<jenis_kelamin>laki-laki</jenis_kelamin>
		<asal>bandung</asal>
		<no_hp code="+62">08121068924</no_hp>
		<kendaraan>
		<jurusan no.sim="11200301">Bandung-Jakarta</jurusan>
		<identitas_mobil plat="B">Counter</identitas_mobil>
		<maks_penumpang>30</maks_penumpang>
		<maks_barang satuan="kg">60</maks_barang>
		</kendaraan>
	</biodata>
</Data_sopir>
